feat: profile picture shown in lobby
Jameskmonger/creature-chess pull request #446
Opened 2021-07-26 14:59 UTC by jameshallam93

closes #420 

Show profile picture in lobby. For empty spots, show no_player_img

2021-07-26 17:42 UTC, Jameskmonger requested changes

2021-07-26 17:42 UTC, Jameskmonger commented on packages/app/src/lobby/lobbyPage.tsx
> +			<LobbyPlayerBanner
This also needs a key! Even if you're not using `map`, you need a key if you're rendering things inside an array (which we are, as `botElements` is an array)

2021-07-26 17:42 UTC, Jameskmonger commented on packages/ui/src/lobbyPlayerBanner/lobbyPlayerBanner.tsx
> +		<div key={player?.id} className="player">
Move the key up a level, individual components should not know about their own key, the key is the concern of the thing rendering multiple of them

2021-07-26 17:42 UTC, Jameskmonger commented on packages/ui/stories/lobbyPlayerBanner/lobbyPlayerBanner.stories.tsx
> +}
Love it ,nice work and hope you liked using storybook

2021-07-26 17:42 UTC, Jameskmonger commented on packages/ui/src/lobbyPlayerBanner/lobbyPlayerBanner.tsx
> +			<div key={Math.floor(Math.random() * 1000)} className="player bot">
avoid random keys https://codeburst.io/how-to-not-react-common-anti-patterns-and-gotchas-in-react-40141fe0dcd

2021-07-27 11:01 UTC, jameshallam93 reviewed
Accidental review

2021-07-27 12:33 UTC, Jameskmonger approved these changes

2021-07-27 12:44 UTC, merged